font_family      JetBrainsMono Nerd Font
font_size        12.0
bold_font        auto

cursor_shape     beam
cursor_blink     yes
cursor     #137a7f
cursor_text_color #282626

background       #282626
background_opacity 0.70
foreground       #e0e0e0

window_padding_width 8
scrollback_lines 10000

color0  #282626
color1  #e12885
color2  #f4cccc
color3  #bec8d1
color4  #86cecb
color5  #65b1b1
color6  #86cecb
color7  #e0e0e0

color8  #5c5f77
color9  #e8dd4c
