
background            #1f1f1f
foreground            #d7afa8

cursor                #ffb6c1
cursor_text_color     #1f1f1f
selection_background  #696969
selection_foreground  #ffb6c1

# Black / Gray
color0   #2a2a2a
color8   #696969

# Red / Pink
color1   #ffb6c1
color9   #ffc0cb

# Green (soft pastel harmony)
color2   #a9c3b6
color10  #c6ddd3

# Yellow (warm highlight)
color3   #f2d7a8
color11  #ffe5b4

# Blue (muted lavender-blue)
color4   #9aa7c7
color12  #c8d0e6

# Magenta (rose)
color5   #d7a8c8
color13  #f0c2dd

# Cyan (soft mint)
color6   #9fbfc0
color14  #bdd8d6


# White
color7   #e6dcd9
color15  #ffffff

# Tabs
active_tab_background     #d7afa8
active_tab_foreground     #1f1f1f
inactive_tab_background   #2a2a2a
inactive_tab_foreground   #696969
tab_bar_background        #1a1a1a

# Borders
active_border_color       #ffc0cb
inactive_border_color     #3a3a3a

# URL
url_color                 #ffb6c1
